name: spykshrk_realtime
channels:
- defaults
- conda-forge
- edeno
dependencies:
  - cython
  - dask
  - holoviews
  - jupyter
  - matplotlib
  - mpi4py
  - networkx
  - numpy
  - pandas
  - scipy
  - loren_frank_data_processing
  - ipyparallel
